sudo: required

language: java

addons:
  hosts:
    - pcap4j-test
  hostname: pcap4j-test

branches:
  only:
    - v1

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk7
      env: COVERALLS=yes
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk7
      env: JDK6=yes
  fast_finish: true

cache:
  directories:
    - $HOME/.m2

install:
  - git clone -b libpcap-1.7.4 git://github.com/the-tcpdump-group/libpcap.git libpcap
  - cd libpcap
  - ./configure
  - make && sudo make install
  - cd ..
  - $TRAVIS_BUILD_DIR/mvnw --version

script:
  - |
    if [ "${JDK6}" = "yes"  ]
    then
      export /usr/lib/jvm/java-6-openjdk-amd64/
    fi
    if [ "${COVERALLS}" = "yes"  ]
    then
      sudo $TRAVIS_BUILD_DIR/mvnw -Dorg.pcap4j.core.pcapLibName=/usr/local/lib/libpcap.so -B -DserviceJobId=$TRAVIS_JOB_ID -Dorg.pcap4j.core.test.enableTimestampPrecisionTests=true -P test-coverage verify coveralls:report
    else
      sudo $TRAVIS_BUILD_DIR/mvnw -Dorg.pcap4j.core.pcapLibName=/usr/local/lib/libpcap.so -B install
    fi

notifications:
  email:
    recipients:
      - kaitoy@pcap4j.org
    on_success: change
    on_failure: always
