sudo: required

language: java

branches:
  except:
    - gh-pages

matrix:
  include:
    - jdk: oraclejdk8
  fast_finish: true

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
#    - $HOME/.gradle/caches

install:
  - git clone -b libpcap-1.7.4 git://github.com/the-tcpdump-group/libpcap.git libpcap
  - cd libpcap
  - ./configure
  - make && sudo make install
  - cd ..

script:
  # sudo is needed for some unit tests.
  - sudo ./gradlew build jacocoTestReport -Dorg.pcap4j.core.pcapLibName=/usr/local/lib/libpcap.so -Dorg.pcap4j.core.test.enableTimestampPrecisionTests=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - kaitoy@pcap4j.org
    on_success: change
    on_failure: always
